### ISSUE TITLE
1.1.x Compatibility

### ISSUE THREAD

**Issue by citrus** [citrus/spree_variant_options#27]
We need to make spree_variant_options Compatible with Spree 1.1.x....

I'm working on this today but thought I'd open an issue to save someone from doing this as well.

-Spencer

/cc @sbounmy

**Comment by sbounmy** [comment]
@citrus Roger that :)

**Comment by citrus** [comment]
I just pushed 66ce05f13a71056c3ecd973a54e4baa2d8f42228 to the 1.1.x branch.. It looks like most of the features are failing due to inventory settings and related. Can you pull and see if there's anything obvious that I'm overlooking?

Here's what I'm getting for the unit tests:

```
Run options: 

# Running tests:

FFFFF...............

Finished tests in 11.187546s, 1.7877 tests/s, 2.7709 assertions/s.

  1) Failure:
test: with track inventory levels should allow choose out of stock variants. (ProductTest) [/Users/Spencer/RoR/gems/spree_variant_options/test/integration/variant_test.rb:73]:
Failed assertion, no message given.

  2) Failure:
test: with track inventory levels should choose in stock variant. (ProductTest) [/Users/Spencer/RoR/gems/spree_variant_options/test/integration/variant_test.rb:89]:
Failed assertion, no message given.

  3) Failure:
test: with track inventory levels should disallow choose out of stock variants. (ProductTest) [/Users/Spencer/RoR/gems/spree_variant_options/test/integration/variant_test.rb:59]:
<"true"> expected but was
<"false">.

  4) Failure:
test: with track inventory levels should should select first instock variant when default_instock is true. (ProductTest) [/Users/Spencer/RoR/gems/spree_variant_options/test/integration/variant_test.rb:107]:
Failed assertion, no message given.

  5) Failure:
test: without inventory tracking should choose variant with track_inventory_levels to false. (ProductTest) [/Users/Spencer/RoR/gems/spree_variant_options/test/integration/variant_test.rb:148]:
Failed assertion, no message given.

20 tests, 31 assertions, 5 failures, 0 errors, 0 skips
rake aborted!
Command failed with status (5): [/Users/Spencer/.rbenv/versions/1.9.3-p125/...]

Tasks: TOP => default => test
(See full trace by running task with --trace)
```

And here's the features:

```
/Users/Spencer/.rbenv/versions/1.9.3-p125/bin/ruby -S bundle exec cucumber --format pretty
Using the default profile...
@javascript @admin
Feature: Admin option type values

  In order to make selectable options
  As an admin
  I want to manage option type values

  Background:                            # features/spree/admin/option_types.feature:8
    Given I have a product with variants # features/step_definitions/variant_options.rb:30

  Scenario: Index option values                                          # features/spree/admin/option_types.feature:11
    Given I'm on the edit admin option type page for option type "Size"  # features/step_definitions/web_steps.rb:59
    Then I should see option values for small, medium, large and x-large # features/step_definitions/option_values.rb:1

  Scenario: Create a new option values                                              # features/spree/admin/option_types.feature:15
    Given I'm on the edit admin option type page for option type "Size"             # features/step_definitions/web_steps.rb:59
    Then I follow "Add Option Value"                                                # features/step_definitions/web_steps.rb:93
    And I fill in the option value fields for the new option value                  # features/step_definitions/option_values.rb:10
    When I press "Update"                                                           # features/step_definitions/web_steps.rb:79
    Then I should see option values for small, medium, large, x-large and xxx-large # features/step_definitions/option_values.rb:1
    And I should see image "1.jpg"                                                  # features/step_definitions/option_values.rb:27

  Scenario: Update an existing option value                                 # features/spree/admin/option_types.feature:23
    Given I'm on the edit admin option type page for option type "Size"     # features/step_definitions/web_steps.rb:59
    When I fill in the option value fields for option value "Medium"        # features/step_definitions/option_values.rb:10
    And I press "Update"                                                    # features/step_definitions/web_steps.rb:79
    Then I should see option values for small, large, x-large and xxx-large # features/step_definitions/option_values.rb:1
    And I should see image "1.jpg"                                          # features/step_definitions/option_values.rb:27

  Scenario: Delete an existing option value                             # features/spree/admin/option_types.feature:30
    Given I'm on the edit admin option type page for option type "Size" # features/step_definitions/web_steps.rb:59
    When I follow "Remove" for option type "Small"                      # features/step_definitions/option_values.rb:33
    And I press "Update"                                                # features/step_definitions/web_steps.rb:79
    Then I should see option values for medium, large and x-large       # features/step_definitions/option_values.rb:1

@javascript
Feature: Products should have variant options

  In order to purchase a product
  As a customer
  I want to select a variant

  Scenario: Display options when visiting a product            # features/spree/variant_options.feature:8
    Given I have a product with variants                       # features/step_definitions/variant_options.rb:30
    And I'm on the product page for the first product          # features/step_definitions/web_steps.rb:59
    Then the source should contain the options hash            # features/step_definitions/variant_options.rb:105
    And I should see enabled links for the first option type   # features/step_definitions/variant_options.rb:112
    And I should see disabled links for the second option type # features/step_definitions/variant_options.rb:112
      <"option-value locked"> expected but was
      <"option-value">. (MiniTest::Assertion)
      ./features/step_definitions/variant_options.rb:126:in `block (2 levels) in <top (required)>'
      ./features/step_definitions/variant_options.rb:120:in `/^I should see (enabled|disabled)+ links for the ((?!option).*) option type$/'
      features/spree/variant_options.feature:13:in `And I should see disabled links for the second option type'
    And I should have a hidden input for the selected variant  # features/step_definitions/variant_options.rb:131
    And the add to cart button should be disabled              # features/step_definitions/variant_options.rb:139

  Scenario: Display option images when visiting a product            # features/spree/variant_options.feature:17
    Given I have a product with variants                             # features/step_definitions/variant_options.rb:30
    And the first option type has an option value with image "1.jpg" # features/step_definitions/variant_options.rb:42
    And I'm on the product page for the first product                # features/step_definitions/web_steps.rb:59
    Then I should see image "1.jpg" within the first option value    # features/step_definitions/variant_options.rb:47

  Scenario: Interact with options for a product                # features/spree/variant_options.feature:23
    Given I have a product with variants                       # features/step_definitions/variant_options.rb:30
    And I'm on the product page for the first product          # features/step_definitions/web_steps.rb:59
    When I follow "Small" within the first set of options      # features/step_definitions/web_steps.rb:97
    Then I should see enabled links for the second option type # features/step_definitions/variant_options.rb:112
      <"option-value in-stock"> expected but was
      <"option-value">. (MiniTest::Assertion)
      ./features/step_definitions/variant_options.rb:126:in `block (2 levels) in <top (required)>'
      ./features/step_definitions/variant_options.rb:120:in `/^I should see (enabled|disabled)+ links for the ((?!option).*) option type$/'
      features/spree/variant_options.feature:27:in `Then I should see enabled links for the second option type'
    And the add to cart button should be disabled              # features/step_definitions/variant_options.rb:139
    When I follow "Green" within the second set of options     # features/step_definitions/web_steps.rb:97
    Then the add to cart button should be enabled              # features/step_definitions/variant_options.rb:139
    When I follow "Medium" within the first set of options     # features/step_definitions/web_steps.rb:97
    And I should see enabled links for the second option type  # features/step_definitions/variant_options.rb:112
    And the add to cart button should be disabled              # features/step_definitions/variant_options.rb:139
    When I follow "Red" within the second set of options       # features/step_definitions/web_steps.rb:97
    And the add to cart button should be enabled               # features/step_definitions/variant_options.rb:139

  Scenario: Should show out of stock for appropriate variants             # features/spree/variant_options.feature:37
    Given I don't allow backorders                                        # features/step_definitions/variant_options.rb:23
    And I have a product with variants                                    # features/step_definitions/variant_options.rb:30
    And the "Small Green" variant is out of stock                         # features/step_definitions/variant_options.rb:55
    And I'm on the product page for the first product                     # features/step_definitions/web_steps.rb:59
    When I follow "Small" within the first set of options                 # features/step_definitions/web_steps.rb:97
    Then I should see an out-of-stock link for "Green"                    # features/step_definitions/variant_options.rb:145
      <"option-value out-of-stock"> expected but was
      <"option-value">. (MiniTest::Assertion)
      ./features/step_definitions/variant_options.rb:150:in `block (2 levels) in <top (required)>'
      ./features/step_definitions/variant_options.rb:148:in `each'
      ./features/step_definitions/variant_options.rb:148:in `/^I should see an (out-of|in)-stock link for "([^"]*)"$/'
      features/spree/variant_options.feature:43:in `Then I should see an out-of-stock link for "Green"'
    And I should see an in-stock link for "Red, Blue, Black, White, Gray" # features/step_definitions/variant_options.rb:145

  Scenario: Should allow backorders of in stock variants                  # features/spree/variant_options.feature:46
    Given I allow backorders                                              # features/step_definitions/variant_options.rb:23
    And I have a product with variants                                    # features/step_definitions/variant_options.rb:30
    And the "Small Green" variant is out of stock                         # features/step_definitions/variant_options.rb:55
    And I'm on the product page for the first product                     # features/step_definitions/web_steps.rb:59
    When I follow "Small" within the first set of options                 # features/step_definitions/web_steps.rb:97
    Then I should see an in-stock link for "Green"                        # features/step_definitions/variant_options.rb:145
      <"option-value in-stock"> expected but was
      <"option-value">. (MiniTest::Assertion)
      ./features/step_definitions/variant_options.rb:150:in `block (2 levels) in <top (required)>'
      ./features/step_definitions/variant_options.rb:148:in `each'
      ./features/step_definitions/variant_options.rb:148:in `/^I should see an (out-of|in)-stock link for "([^"]*)"$/'
      features/spree/variant_options.feature:52:in `Then I should see an in-stock link for "Green"'
    And I should see an in-stock link for "Red, Blue, Black, White, Gray" # features/step_definitions/variant_options.rb:145

  Scenario: Should clear current selection                      # features/spree/variant_options.feature:55
    Given I have a product with variants                        # features/step_definitions/variant_options.rb:30
    And I'm on the product page for the first product           # features/step_definitions/web_steps.rb:59
    When I follow "Small" within the first set of options       # features/step_definitions/web_steps.rb:97
    And I click the current clear button                        # features/step_definitions/variant_options.rb:88
      Element is not currently visible and so may not be interacted with (Selenium::WebDriver::Error::ElementNotVisibleError)
      [remote server] file:///var/folders/73/xm1ptfns0rgc64ns7d7lgf1m0000gn/T/webdriver-profile20120514-17343-13ri42t/extensions/fxdriver@googlecode.com/components/command_processor.js:5780:in `unknown'
      [remote server] file:///var/folders/73/xm1ptfns0rgc64ns7d7lgf1m0000gn/T/webdriver-profile20120514-17343-13ri42t/extensions/fxdriver@googlecode.com/components/command_processor.js:9828:in `unknown'
      [remote server] file:///var/folders/73/xm1ptfns0rgc64ns7d7lgf1m0000gn/T/webdriver-profile20120514-17343-13ri42t/extensions/fxdriver@googlecode.com/components/command_processor.js:9849:in `unknown'
      [remote server] file:///var/folders/73/xm1ptfns0rgc64ns7d7lgf1m0000gn/T/webdriver-profile20120514-17343-13ri42t/extensions/fxdriver@googlecode.com/components/command_processor.js:9854:in `unknown'
      [remote server] file:///var/folders/73/xm1ptfns0rgc64ns7d7lgf1m0000gn/T/webdriver-profile20120514-17343-13ri42t/extensions/fxdriver@googlecode.com/components/command_processor.js:9800:in `unknown'
      ./features/step_definitions/variant_options.rb:95:in `/^I click the (current|first|last) clear button$/'
      features/spree/variant_options.feature:59:in `And I click the current clear button'
    Then I should see disabled links for the second option type # features/step_definitions/variant_options.rb:112
    And I should see enabled links for the first option type    # features/step_definitions/variant_options.rb:112

  Scenario: Should clear current selection and maintain parent selection # features/spree/variant_options.feature:63
    Given I have a product with variants                                 # features/step_definitions/variant_options.rb:30
    And I'm on the product page for the first product                    # features/step_definitions/web_steps.rb:59
    When I follow "Small" within the first set of options                # features/step_definitions/web_steps.rb:97
    And I follow "Green" within the second set of options                # features/step_definitions/web_steps.rb:97
    Then the add to cart button should be enabled                        # features/step_definitions/variant_options.rb:139
    And I click the last clear button                                    # features/step_definitions/variant_options.rb:88
      Element is not currently visible and so may not be interacted with (Selenium::WebDriver::Error::ElementNotVisibleError)
      [remote server] file:///var/folders/73/xm1ptfns0rgc64ns7d7lgf1m0000gn/T/webdriver-profile20120514-17343-13ri42t/extensions/fxdriver@googlecode.com/components/command_processor.js:5780:in `unknown'
      [remote server] file:///var/folders/73/xm1ptfns0rgc64ns7d7lgf1m0000gn/T/webdriver-profile20120514-17343-13ri42t/extensions/fxdriver@googlecode.com/components/command_processor.js:9828:in `unknown'
      [remote server] file:///var/folders/73/xm1ptfns0rgc64ns7d7lgf1m0000gn/T/webdriver-profile20120514-17343-13ri42t/extensions/fxdriver@googlecode.com/components/command_processor.js:9849:in `unknown'
      [remote server] file:///var/folders/73/xm1ptfns0rgc64ns7d7lgf1m0000gn/T/webdriver-profile20120514-17343-13ri42t/extensions/fxdriver@googlecode.com/components/command_processor.js:9854:in `unknown'
      [remote server] file:///var/folders/73/xm1ptfns0rgc64ns7d7lgf1m0000gn/T/webdriver-profile20120514-17343-13ri42t/extensions/fxdriver@googlecode.com/components/command_processor.js:9800:in `unknown'
      ./features/step_definitions/variant_options.rb:95:in `/^I click the (current|first|last) clear button$/'
      features/spree/variant_options.feature:69:in `And I click the last clear button'
    Then I should see "Small" selected within the first set of options   # features/step_definitions/variant_options.rb:155
    And I should see enabled links for the second option type            # features/step_definitions/variant_options.rb:112
    And the add to cart button should be disabled                        # features/step_definitions/variant_options.rb:139

  Scenario: Should clear current selection and parent selection # features/spree/variant_options.feature:74
    Given I have a product with variants                        # features/step_definitions/variant_options.rb:30
    And I'm on the product page for the first product           # features/step_definitions/web_steps.rb:59
    When I follow "Small" within the first set of options       # features/step_definitions/web_steps.rb:97
    And I follow "Green" within the second set of options       # features/step_definitions/web_steps.rb:97
    Then the add to cart button should be enabled               # features/step_definitions/variant_options.rb:139
    And I click the first clear button                          # features/step_definitions/variant_options.rb:88
      Element is not currently visible and so may not be interacted with (Selenium::WebDriver::Error::ElementNotVisibleError)
      [remote server] file:///var/folders/73/xm1ptfns0rgc64ns7d7lgf1m0000gn/T/webdriver-profile20120514-17343-13ri42t/extensions/fxdriver@googlecode.com/components/command_processor.js:5780:in `unknown'
      [remote server] file:///var/folders/73/xm1ptfns0rgc64ns7d7lgf1m0000gn/T/webdriver-profile20120514-17343-13ri42t/extensions/fxdriver@googlecode.com/components/command_processor.js:9828:in `unknown'
      [remote server] file:///var/folders/73/xm1ptfns0rgc64ns7d7lgf1m0000gn/T/webdriver-profile20120514-17343-13ri42t/extensions/fxdriver@googlecode.com/components/command_processor.js:9849:in `unknown'
      [remote server] file:///var/folders/73/xm1ptfns0rgc64ns7d7lgf1m0000gn/T/webdriver-profile20120514-17343-13ri42t/extensions/fxdriver@googlecode.com/components/command_processor.js:9854:in `unknown'
      [remote server] file:///var/folders/73/xm1ptfns0rgc64ns7d7lgf1m0000gn/T/webdriver-profile20120514-17343-13ri42t/extensions/fxdriver@googlecode.com/components/command_processor.js:9800:in `unknown'
      ./features/step_definitions/variant_options.rb:95:in `/^I click the (current|first|last) clear button$/'
      features/spree/variant_options.feature:80:in `And I click the first clear button'
    Then I should not see a selected option                     # features/step_definitions/variant_options.rb:168
    And I should see disabled links for the second option type  # features/step_definitions/variant_options.rb:112
    And I should see enabled links for the first option type    # features/step_definitions/variant_options.rb:112
    And the add to cart button should be disabled               # features/step_definitions/variant_options.rb:139

  Scenario: Should add proper variant to cart             # features/spree/variant_options.feature:86
    Given I have a product with variants                  # features/step_definitions/variant_options.rb:30
    And I'm on the product page for the first product     # features/step_definitions/web_steps.rb:59
    When I follow "Small" within the first set of options # features/step_definitions/web_steps.rb:97
    And I follow "Green" within the second set of options # features/step_definitions/web_steps.rb:97
    Then the add to cart button should be enabled         # features/step_definitions/variant_options.rb:139
    And I press "Add To Cart"                             # features/step_definitions/web_steps.rb:79
    Then I should be on the cart page                     # features/step_definitions/variant_options.rb:174
      <"/cart"> expected but was
      <"/orders/populate">. (MiniTest::Assertion)
      ./features/step_definitions/variant_options.rb:175:in `/^I should be on the cart page$/'
      features/spree/variant_options.feature:93:in `Then I should be on the cart page'
    And I should see "Size: Small, Color: Green"          # features/step_definitions/web_steps.rb:120

  Scenario: Should auto-select variant if its the only option               # features/spree/variant_options.feature:96
    Given I have a product with variants                                    # features/step_definitions/variant_options.rb:30
    And I have an "XXL Turquoise" variant                                   # features/step_definitions/variant_options.rb:65
    And I'm on the product page for the first product                       # features/step_definitions/web_steps.rb:59
    When I follow "XXL" within the first set of options                     # features/step_definitions/web_steps.rb:97
    Then I should see "Turquoise" selected within the second set of options # features/step_definitions/variant_options.rb:155
      Failed assertion, no message given. (MiniTest::Assertion)
      ./features/step_definitions/variant_options.rb:164:in `block (2 levels) in <top (required)>'
      ./features/step_definitions/variant_options.rb:161:in `/^I should see "([^"]*)" selected within the (first|second|last) set of options$/'
      features/spree/variant_options.feature:101:in `Then I should see "Turquoise" selected within the second set of options'
    And the add to cart button should be enabled                            # features/step_definitions/variant_options.rb:139
    When I follow "Small" within the first set of options                   # features/step_definitions/web_steps.rb:97
    Then the add to cart button should be disabled                          # features/step_definitions/variant_options.rb:139

  Scenario: Should adjust price according to variant           # features/spree/variant_options.feature:106
    Given I have a product with variants                       # features/step_definitions/variant_options.rb:30
    And I have an "XXS Turquoise" variant for $29.99           # features/step_definitions/variant_options.rb:65
    And I have an "XXS Pink" variant for $24.99                # features/step_definitions/variant_options.rb:65
    And I'm on the product page for the first product          # features/step_definitions/web_steps.rb:59
    When I follow "XXS" within the first set of options        # features/step_definitions/web_steps.rb:97
    Then I should see "$24.99 - $29.99" in the price           # features/step_definitions/web_steps.rb:124
      Failed assertion, no message given. (MiniTest::Assertion)
      ./features/step_definitions/web_steps.rb:126:in `block (2 levels) in <top (required)>'
      ./features/step_definitions/web_steps.rb:125:in `/^I should see "([^"]*)" in (.*)$/'
      features/spree/variant_options.feature:112:in `Then I should see "$24.99 - $29.99" in the price'
    When I follow "Turquoise" within the second set of options # features/step_definitions/web_steps.rb:97
    Then I should see "$29.99" in the price                    # features/step_definitions/web_steps.rb:124
    And the add to cart button should be enabled               # features/step_definitions/variant_options.rb:139
    When I follow "Pink" within the second set of options      # features/step_definitions/web_steps.rb:97
    Then I should see "$24.99" in the price                    # features/step_definitions/web_steps.rb:124
    And the add to cart button should be enabled               # features/step_definitions/variant_options.rb:139

  Scenario: Should show the master price when all variants are out of stock   # features/spree/variant_options.feature:120
    Given I don't allow backorders                                            # features/step_definitions/variant_options.rb:23
    And I have a product with variants                                        # features/step_definitions/variant_options.rb:30
    And all the variants are out of stock                                     # features/step_definitions/variant_options.rb:61
    And I have a "master" variant for $20.99                                  # features/step_definitions/variant_options.rb:65
    When I'm on the product page for the first product                        # features/step_definitions/web_steps.rb:59
    And I should see an out-of-stock link for "Small, Medium, Large, X-Large" # features/step_definitions/variant_options.rb:145
    And I should see disabled links for the second option type                # features/step_definitions/variant_options.rb:112
      <"option-value locked"> expected but was
      <"option-value">. (MiniTest::Assertion)
      ./features/step_definitions/variant_options.rb:126:in `block (2 levels) in <top (required)>'
      ./features/step_definitions/variant_options.rb:120:in `/^I should see (enabled|disabled)+ links for the ((?!option).*) option type$/'
      features/spree/variant_options.feature:127:in `And I should see disabled links for the second option type'
    Then I should see "$20.99" in the price                                   # features/step_definitions/web_steps.rb:124

Failing Scenarios:
cucumber features/spree/variant_options.feature:8 # Scenario: Display options when visiting a product
cucumber features/spree/variant_options.feature:23 # Scenario: Interact with options for a product
cucumber features/spree/variant_options.feature:37 # Scenario: Should show out of stock for appropriate variants
cucumber features/spree/variant_options.feature:46 # Scenario: Should allow backorders of in stock variants
cucumber features/spree/variant_options.feature:55 # Scenario: Should clear current selection
cucumber features/spree/variant_options.feature:63 # Scenario: Should clear current selection and maintain parent selection
cucumber features/spree/variant_options.feature:74 # Scenario: Should clear current selection and parent selection
cucumber features/spree/variant_options.feature:86 # Scenario: Should add proper variant to cart
cucumber features/spree/variant_options.feature:96 # Scenario: Should auto-select variant if its the only option
cucumber features/spree/variant_options.feature:106 # Scenario: Should adjust price according to variant
cucumber features/spree/variant_options.feature:120 # Scenario: Should show the master price when all variants are out of stock

16 scenarios (11 failed, 5 passed)
119 steps (11 failed, 32 skipped, 76 passed)
0m49.167s
rake aborted!
Command failed with status (1): [/Users/Spencer/.rbenv/versions/1.9.3-p125/...]

Tasks: TOP => cucumber
(See full trace by running task with --trace)
```

Thanks!

**Comment by sbounmy** [comment]
hey @citrus, I will try to investigate asap !

**Comment by mraaroncruz** [comment]
Are there any updates on this?
Thanks

**Comment by sbounmy** [comment]
hi @pferdefleisch,

I posted on spree's mailing list : https://groups.google.com/forum/?fromgroups#!searchin/spree-user/asset/spree-user/hPGHsajnruY/HguWTinJ7_QJ

I did not have any answer yet, but I will try to take a look this week-end.

**Comment by mraaroncruz** [comment]
Thanks again.

**Comment by citrus** [comment]
Closed thanks to @sbounmy's awesome work!! :beer: :beer:
